services:
  lora-maker:
    build:
      context: .
      target: dev
      args:
        - NODE_VERSION=node:22-alpine
    ports:
      - "3000:3000"
    develop:
      watch:
        - action: sync
          path: .
          target: /app
          ignore:
            - node_modules
        - action: rebuild
          path: package.json
